[workspace]
authors = ["Elly <ellyfiah@gmail.com>"]
channels = ["conda-forge"]
name = "ProjectCyber"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.5.0,<5"
pandas = ">=2.3.3,<3"
numpy = ">=2.3.5,<3"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"
plotly = ">=6.5.0,<7"
ua-parser = ">=1.0.1,<2"
regex = "*"
geoip2 = ">=4.8.0,<5"
user-agents = ">=2.2.0,<3"
geopy = ">=2.4.1,<3"
